// Code generated by mockery v2.49.1. DO NOT EDIT.

package mocks

import (
	httpclient "health-check/pkg/httpclient"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// SendGetRequest provides a mock function with given fields: url
func (_m *Client) SendGetRequest(url string) (*httpclient.Response, error) {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for SendGetRequest")
	}

	var r0 *httpclient.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*httpclient.Response, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) *httpclient.Response); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*httpclient.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
